name: Pull request

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, labeled, synchronize, ready_for_review]

jobs:
  lint_and_test:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --only=main --no-interaction --no-ansi
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Run linters and tests
        run: |
          make dc/ci/check/lint/black
          make dc/ci/check/lint/deps
          make dc/ci/check/lint/flake8
          make dc/ci/check/lint/isort
          make dc/ci/check/mypy
          make dc/ci/test
